### ISSUE TITLE
Bug `I do not know the key '/tikz/Black' and I am going to  ignore it.`

### ISSUE THREAD

**Issue by chupinmaxime** [cpierquet/PixelArtTikz#1]
Bonjour, 
Petit exemple simple qui montre un problème à l’utilisation du package. 

```latex
\documentclass{article}
 \usepackage{PixelArtTikz}


%création du fichier csv
\begin{filecontents*}[overwrite]{pixelart.csv}
  -,-,-,-,-,-,4,4,4,4,-,-,-,-,-,-
  -,-,-,-,4,4,1,1,1,1,4,4,-,-,-,-
  -,-,-,4,1,1,1,1,1,1,1,1,4,-,-,-
  -,-,4,1,1,1,1,1,1,1,1,1,1,4,-,-
  -,-,4,1,1,1,1,1,1,1,1,1,1,4,-,-
  -,4,1,9,9,1,1,1,1,1,1,9,9,1,4,-
  -,4,9,9,9,9,4,4,4,4,9,9,9,9,4,-
  -,4,9,4,9,9,4,4,4,4,9,4,9,9,4,-
  -,4,1,9,9,9,4,4,4,4,9,9,9,1,4,-
  -,-,4,1,1,9,4,4,4,4,9,1,1,4,-,-
  -,-,4,1,1,1,4,4,4,4,1,1,1,4,-,-
  -,-,-,4,1,1,1,4,4,1,1,1,4,-,-,-
  -,-,4,3,1,1,1,1,1,1,1,1,3,4,-,-
  -,4,6,3,1,1,1,1,1,1,1,1,3,6,4,-
  -,4,6,6,1,1,1,1,1,1,1,1,6,6,4,-
  -,4,6,6,1,1,1,1,1,1,1,1,6,6,4,-
  -,4,6,4,1,1,1,4,4,1,1,1,4,6,4,-
  2,2,4,2,4,4,4,2,2,4,4,4,2,4,2,2
  2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
  2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
  -,-,-,-,-,4,1,1,1,1,4,-,-,-,-,-
  -,-,-,-,-,-,4,1,1,4,-,-,-,-,-,-
  -,-,-,-,-,-,-,4,4,-,-,-,-,-,-,-
\end{filecontents*}


\begin{document}

 \PixelArtTikz[Codes=123469,Couleurs={Red,Brown,Yellow,Black,Blue,White},Correction,Unite=0.35,BordCases=false]{pixelart.csv}

\end{document}
```

**Comment by cpierquet** [comment]
J'ai oublié de préciser dans la doc que les couleurs doivent être gérées par l'utilisateur, le package ne chargeant pas de package spécifique concernant les couleurs... Et bien sûr j'ai utilisé du `xcolor` avec `svgnames` dans la documentation...

Donc sans package supplémentaire, ce code compilera :
`\PixelArtTikz[Codes=123469,Couleurs={red,brown,yellow,black,blue,white},Correction,Unite=0.35,BordCases=false]{pixelart.csv}`
![image](https://user-images.githubusercontent.com/45103962/232986153-3bd1e605-a147-4bdf-83cf-d864583047fc.png)

**Comment by chupinmaxime** [comment]
Oui, j'avais bien compris :) mais je signalais car il me semble qu'il faut utiliser des exemples complets (ou presque) et le moins de sur-couches possible dans une documentation.

**Comment by cpierquet** [comment]
Oui ! J'avais précisé dans la doc, mais pas de manière suffisamment explicite... J'ai corrigé la doc avec la suppression de `xcolor`, et l'utilisation des couleurs de base :-)

**Comment by chupinmaxime** [comment]
Super !
